version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - run:
          name: "Install build system dependencies"
          command: |
            sudo apt-get update
            sudo apt-get install python3 python3-setuptools
            python3 -m pip install setuptools
      - checkout
      - run:
          name: "Build PROTEUS docker image"
          command: |
            sh build_docker_image.sh

workflows:
  build-workflow:
    jobs:
      - build
